framework:
    workflows:
        order:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Paiement\PaOrder
            initial_marking: created
            places:
                - created
                - validated
                - finished
                - expired
                - canceled
            transitions:
                create_order:
                    from: created
                    to: created
                confirm_order:
                    from: created
                    to: validated
                pay_order:
                    from: validated
                    to: finished
                expire_order:
                    from: created
                    to: expired
                cancel_order:
                    from: [created, validated]
                    to: canceled
